version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: tomcat-spring-integration-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    #volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      #- ./db/init-script.sql:/docker-entrypoint-initdb.d/create_tables.sql
    network_mode: bridge